# Generated by Django 6.0.3 on 2026-06-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField()),
                ('Event_Date', models.DateField()),
                ('Location', models.CharField()),
                ('Category', models.CharField()),
            ],
        ),
    ]
