# Generated by Django 6.0.3 on 2026-06-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='Event_Date',
            new_name='EventDate',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='Event_name',
            new_name='EventName',
        ),
    ]
